language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: ppl-billingandmailing
